/** v3.1 — calendar, read-only tracking and recorded workload analytics. */
let analyticsTrail=[];
let calendarOffset=0,statusIndex=null,statusQuery='',statusLoading=false,statusError='',analyticsData=null,analyticsLoading=false,analyticsError='',analyticsView='Designers',analyticsFrom='',analyticsTo='';
function rollingCalendarHTML(){
  const now=new Date(),base=new Date(now.getFullYear(),now.getMonth()+calendarOffset,1),byDay={};
  activeItems().forEach(i=>{const p=state.projects.find(p=>String(p.ProjectID)===String(i.ProjectID))||{},d=dateOnlyFromAny(i.ItemDueDate||p.DueDate);if(d){const groups=byDay[ymd(d)]||=(new Map()),id=String(p.ProjectID||i.ProjectID);if(!groups.has(id))groups.set(id,{p,items:[]});groups.get(id).items.push(i);}});
  return `<div class="panel"><div class="toolbar"><h3>Item Due Dates</h3><button id="calendarPrev">← Previous month</button><button id="calendarToday">Current month</button><button id="calendarNext">Next month →</button></div><div class="calendarMonths">${[0,1,2].map(offset=>{
    const d=new Date(base.getFullYear(),base.getMonth()+offset,1),count=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();
    return `<section class="monthPanel"><h3>${d.toLocaleDateString('en-PH',{month:'long',year:'numeric'})}</h3><div class="monthGrid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="weekday">${x}</div>`).join('')}${Array.from({length:d.getDay()},()=>'<div class="day empty"></div>').join('')}${Array.from({length:count},(_,index)=>{const date=new Date(d.getFullYear(),d.getMonth(),index+1),key=ymd(date);return `<div class="day ${key===ymd(now)?'today':''}"><b>${index+1}</b>${[...(byDay[key]?.values()||[])].map(({items,p})=>`<button class="calendarItem" data-status-so="${escapeAttr(p.ProjectID)}" title="${escapeAttr(p.ClientName+' • '+items.map(i=>i.ItemDescription).join('; '))}">${escapeHtml(p.SONumber)}</button>`).join('')}</div>`;}).join('')}</div></section>`;
  }).join('')}</div><div class="hint">Active items, using item due date or project due date. Items are grouped by SO on each due date. Click an SO to view its project status.</div></div>`;
}
function bindRollingCalendar(){
  $('calendarPrev').onclick=()=>{calendarOffset--;renderOverview();};$('calendarNext').onclick=()=>{calendarOffset++;renderOverview();};$('calendarToday').onclick=()=>{calendarOffset=0;renderOverview();};bindStatusLinks($('page-overview'));
}
function bindStatusLinks(root,back=null){root.querySelectorAll('[data-status-so]').forEach(b=>b.onclick=()=>openProjectStatus(b.dataset.statusSo,{back}).catch(e=>alert(e.message)));}
function statusItemBullets(items){return `<ul class="statusItemBullets">${items.map(i=>`<li>${escapeHtml(typeof i==='string'?i:(i.Quantity||1)+' '+(i.Unit||'pc')+' '+i.ItemDescription)}</li>`).join('')}</ul>`;}
function statusSummaryItems(p){return p.ItemSummaries||projectItems(p.ProjectID).map(i=>({ItemDescription:i.ItemDescription,Quantity:i.Quantity,Unit:i.Unit}));}
async function loadStatusIndex(){
  statusLoading=true;statusError='';renderProjectStatus();
  try{const res=await api('getStatusIndex',{});statusIndex=res.projects||[];}catch(e){statusError=e.message;}finally{statusLoading=false;if(state.page==='project-status')renderProjectStatus();}
}
function renderProjectStatus(){
  const page=$('page-project-status'),old=$('statusSearch'),focused=old===document.activeElement,pos=old?.selectionStart;
  page.innerHTML=`<div class="pageTitle"><div><h1>Project Status</h1><div class="hint">Search all projects, including completed projects. Project details are read-only; staff can submit follow-ups.</div></div><button id="statusRefresh">Refresh</button></div><input id="statusSearch" placeholder="SO#, client, item, designer, coordinator…" value="${escapeAttr(statusQuery)}"><div id="statusResults"></div>`;
  const list=(statusIndex||state.projects).filter(p=>[p.SONumber,p.ClientName,p.ProjectSummary,p.Designers,p.Detailers,p.Coordinator,p.OverallStatus].join(' ').toLowerCase().includes(statusQuery.toLowerCase()));
  $('statusResults').innerHTML=statusLoading?'<p>Loading projects…</p>':statusError?`<p>${escapeHtml(statusError)}</p>`:list.map(p=>`<button class="statusResult" data-status-so="${escapeAttr(p.ProjectID)}"><b>SO ${escapeHtml(p.SONumber)} · ${escapeHtml(p.ClientName)}</b>${statusSummaryItems(p).length?statusItemBullets(statusSummaryItems(p)):'<span class="small">No items yet</span>'}<span class="small">${escapeHtml(p.OverallStatus)} · ${escapeHtml(p.Designers||'Designer unassigned')}</span></button>`).join('')||'<p>No matching projects.</p>';
  $('statusSearch').oninput=e=>{statusQuery=e.target.value;renderProjectStatus();};$('statusRefresh').onclick=loadStatusIndex;bindStatusLinks(page);
  if(focused){$('statusSearch').focus();$('statusSearch').setSelectionRange(pos,pos);}if(!statusIndex&&!statusLoading&&!statusError)loadStatusIndex();
}
async function openProjectStatus(projectId,options={}){
  const res=await api('getProjectHistory',{projectId}),p=res.project||{},items=res.items||[],history=res.history||[];
  $('projectModalTitle').textContent=`Project Status — SO ${p.SONumber}`;$('projectModalBadge').textContent='View only';
  $('projectModalBody').innerHTML=`<div class="panel">${detail('Client',p.ClientName)}<div class="small"><b>Items:</b></div>${statusItemBullets(items.filter(i=>i.Active!=='N'))}${detail('Status',p.OverallStatus)}${detail('Due date',niceDate(p.DueDate))}${detail('Designer(s)',p.Designers)}${detail('Detailer(s)',p.Detailers)}${detail('Coordinator',p.Coordinator)}${detail('Special requirements',p.SpecialRequirements)}${detail('Special hardware notes',p.SpecialHardwareNotes)}</div>
    ${items.filter(i=>i.Active!=='N').map(i=>{const logs=history.filter(h=>String(h.ItemID)===String(i.ItemID)&&h.EventType==='Process_Moved').sort((a,b)=>new Date(a.StartedAt||a.EventAt)-new Date(b.StartedAt||b.EventAt));return `<section class="panel statusItemPanel"><div class="line"><h3>${escapeHtml(i.ItemID)} · ${escapeHtml(i.ItemDescription)}</h3><button class="primary" data-follow-up-item="${escapeAttr(i.ItemID)}">Follow up on item</button></div>${detail('Quantity',(i.Quantity||1)+' '+(i.Unit||'pc'))}${detail('Current process',i.ItemStatus)}${detail('Team',teamName(i.AssignedTeamID))}${detail('Current PIC',i.AssignedPersonnel)}${detail('Due date',niceDate(i.ItemDueDate||p.DueDate))}${detail('Delivery',i.DeliveryStatus)}${detail('Remarks',i.Remarks)}<div class="tableScroll"><table><thead><tr><th>Process</th><th>Start</th><th>End</th><th>Team</th><th>PIC</th><th>Notes / remarks</th></tr></thead><tbody>${logs.map(h=>`<tr><td>${escapeHtml(h.ToValue)}</td><td>${niceDT(h.StartedAt||h.EventAt)}</td><td>${h.FinishedAt?niceDT(h.FinishedAt):'Ongoing'}</td><td>${escapeHtml(teamName(h.TeamID))}</td><td>${escapeHtml(h.Personnel||'Unassigned')}</td><td>${escapeHtml(h.Message)}</td></tr>`).join('')||'<tr><td colspan="6">No recorded process times.</td></tr>'}</tbody></table></div></section>`;}).join('')}
    <section class="panel"><h3>Notes and follow-ups</h3>${history.filter(h=>['Note','Follow_Up'].includes(h.EventType)).map(h=>`<div class="historyEvent"><b>${escapeHtml(h.Actor)}</b> · ${niceDT(h.EventAt)}<p>${h.ItemID?`<span class="small">Item: ${escapeHtml(h.ItemID)} · </span>`:''}${escapeHtml(h.Message)}</p></div>`).join('')||'<p>No notes.</p>'}</section><section id="followUpFields" class="panel" hidden><h3 id="followUpTarget">Project follow-up</h3><label>Your name<input id="followUpName" maxlength="120"></label><label>Follow-up notes<textarea id="followUpNotes" maxlength="2000"></textarea></label><button id="submitFollowUp" class="primary">Send follow-up</button><div id="followUpResult" role="status"></div></section>`;
  let followUpItemId='';
  $('projectModalFooter').innerHTML=`${options.back?'<button id="statusBack">← Back</button>':''}<button data-close="projectModal">Close</button><button id="showFollowUp" class="primary">Follow up on project</button>`;
  if(options.back)$('statusBack').onclick=options.back;
  const showFollowUp=(itemId='')=>{followUpItemId=itemId;const item=items.find(i=>String(i.ItemID)===String(itemId));$('followUpTarget').textContent=item?'Follow-up — '+item.ItemID+' · '+item.ItemDescription:'Project follow-up';$('followUpFields').hidden=false;$('followUpName').focus();};
  $('showFollowUp').onclick=()=>showFollowUp();
  $('projectModalBody').querySelectorAll('[data-follow-up-item]').forEach(b=>b.onclick=()=>showFollowUp(b.dataset.followUpItem));
  $('submitFollowUp').onclick=e=>runAction(e,'Sending follow-up…',async()=>{const name=$('followUpName').value.trim(),notes=$('followUpNotes').value.trim();if(!name||!notes)return alert('Your name and notes are required.');const result=await api('followUpProject',{projectId,itemId:followUpItemId,name,notes});await openProjectStatus(projectId,options);$('followUpFields').hidden=false;$('followUpResult').textContent=result._viber?.queued?'Follow-up saved; Viber notification queued.':'Follow-up saved. Viber notification was not queued; check Worker channel configuration.';});
  openModal('projectModal');
}
async function loadAnalytics(){analyticsLoading=true;analyticsError='';renderAnalytics();try{analyticsData=await api('getAnalyticsData',{});}catch(e){analyticsError=e.message;}finally{analyticsLoading=false;if(state.page==='analytics')renderAnalytics();}}
function inAnalyticsPeriod(value){const date=String(value||'').slice(0,10);return (!analyticsFrom||date>=analyticsFrom)&&(!analyticsTo||date<=analyticsTo);}
function analyticsProjects(){return (analyticsData?.projects||[]).filter(p=>p.Active!=='N');}
function analyticsItems(){return (analyticsData?.items||[]).filter(i=>i.Active!=='N');}
function analyticsLogs(){return (analyticsData?.history||[]).filter(h=>h.EventType==='Process_Moved'&&inAnalyticsPeriod(h.StartedAt||h.EventAt));}
function namesIn(value){return [...new Set(splitMultiValue(value))];}
function assignedTo(value,name){return namesIn(value).some(n=>n.toLowerCase()===name.toLowerCase());}
function ongoingProject(p){return !['DELIVERED','CANCELLED','CLOSED','ARCHIVED'].includes(String(p.OverallStatus).toUpperCase());}
function analyticsEntities(){
  if(analyticsView==='Production')return state.teams.map(t=>({id:t.TeamID,name:t.TeamName,type:'team'}));
  const field=analyticsView,role=field==='Designers'?'designer':'detailer';
  const names=new Set(analyticsProjects().flatMap(p=>namesIn(p[field])));state.personnel.filter(p=>personRole(p).toLowerCase().includes(role)).forEach(p=>names.add(personName(p)));
  return [...names].sort().map(name=>({id:name,name,type:field}));
}
function entityRecords(entity){
  const allItems=analyticsItems(),logs=analyticsLogs().filter(h=>entity.type==='team'?String(h.TeamID)===String(entity.id):entity.type==='person'?assignedTo(h.Personnel,entity.name):false);
  const current=allItems.filter(i=>!isDeliveredItem(i)&&(entity.type==='team'?String(i.AssignedTeamID)===String(entity.id):entity.type==='person'?assignedTo(i.AssignedPersonnel,entity.name):false));
  const ids=new Set([...current.map(i=>String(i.ProjectID)),...logs.map(h=>String(h.ProjectID))]);
  const projects=analyticsProjects().filter(p=>['Designers','Detailers'].includes(entity.type)?assignedTo(p[entity.type],entity.name):ids.has(String(p.ProjectID)));
  return {projects,logs,current};
}
function entityStats(entity){
  const {projects,logs,current}=entityRecords(entity),completed=logs.filter(h=>h.FinishedAt&&h.StartedAt&&new Date(h.FinishedAt)>=new Date(h.StartedAt));
  const hours=completed.reduce((sum,h)=>sum+(new Date(h.FinishedAt)-new Date(h.StartedAt))/3600000,0);
  return {projects,logs,current,completed,hours};
}
function renderAnalytics(){
  const page=$('page-analytics');
  page.innerHTML=`<div class="pageTitle"><div><h1>Production Analytics</h1><div class="hint">Recorded workload and process timing for performance review.</div></div><button id="analyticsRefresh">Refresh data</button></div><div class="toolbar">${[['Designers','Designer view'],['Detailers','Detailer view'],['Production','Production view']].map(([key,label])=>`<button data-analytics-view="${key}" class="${analyticsView===key?'primary':''}">${label}</button>`).join('')}</div><div class="toolbar"><label>Process records from<input id="analyticsFrom" type="date" value="${analyticsFrom}"></label><label>Through<input id="analyticsTo" type="date" value="${analyticsTo}"></label></div><div class="hint">Dates filter recorded process starts. Current assignments show the present workload. Recorded elapsed hours include nights and waiting time; they are not labor hours. Designer/detailer project totals use current project assignments. Separate names with semicolons.</div><div id="analyticsContent"></div>`;
  $('analyticsRefresh').onclick=loadAnalytics;page.querySelectorAll('[data-analytics-view]').forEach(b=>b.onclick=()=>{analyticsView=b.dataset.analyticsView;renderAnalytics();});['From','To'].forEach(part=>$('analytics'+part).onchange=e=>{if(part==='From')analyticsFrom=e.target.value;else analyticsTo=e.target.value;renderAnalytics();});
  if(analyticsLoading)$('analyticsContent').innerHTML='<p>Loading analytics…</p>';else if(analyticsError)$('analyticsContent').innerHTML=`<p>${escapeHtml(analyticsError)}</p>`;else if(analyticsData){const entities=analyticsEntities();$('analyticsContent').innerHTML=`<div class="analyticsCards">${entities.map((entity,index)=>{const stats=entityStats(entity),ongoing=stats.projects.filter(ongoingProject);return `<button class="panel analyticsCard" data-entity-index="${index}"><h3>${escapeHtml(entity.name)}</h3><b>${ongoing.length} ongoing projects</b>${analyticsProjectBullets(ongoing)}${entity.type==='team'?`<div>${stats.current.length} assigned items · ${stats.completed.length} ended process records · ${stats.hours.toFixed(1)} recorded elapsed hours</div>`:`<div>${stats.projects.length} total projects · ${stats.projects.filter(p=>String(p.OverallStatus).toUpperCase()==='DELIVERED').length} delivered</div>`}</button>`;}).join('')||'<p>No assignments recorded yet.</p>'}</div>`;page.querySelectorAll('[data-entity-index]').forEach(b=>b.onclick=()=>openAnalyticsEntity(entities[Number(b.dataset.entityIndex)],{reset:true}));}
  if(!analyticsData&&!analyticsLoading&&!analyticsError)loadAnalytics();
}
function analyticsProjectBullets(projects,links=false){return projects.length?`<ul class="analyticsProjectList">${projects.map(p=>`<li>${links?`<button class="projectListLink" data-status-so="${escapeAttr(p.ProjectID)}">SO ${escapeHtml(p.SONumber)} · ${escapeHtml(p.ClientName)}</button><div class="small">${escapeHtml(p.ProjectSummary||'')} · ${escapeHtml(p.OverallStatus||'')} · Due: ${escapeHtml(niceDate(p.DueDate)||'—')}</div>`:`SO ${escapeHtml(p.SONumber)} · ${escapeHtml(p.ClientName)}`}</li>`).join('')}</ul>`:'<p class="small">No projects recorded.</p>';}
function analyticsBack(){if(analyticsTrail.length>1){analyticsTrail.pop();openAnalyticsEntity(analyticsTrail[analyticsTrail.length-1],{backNavigation:true});}else{analyticsTrail=[];closeModal('projectModal');renderAnalytics();}}
function openAnalyticsEntity(entity,options={}){
  if(options.reset)analyticsTrail=[];if(!options.backNavigation)analyticsTrail.push(entity);
  const stats=entityStats(entity),members=entity.type==='team'?personnelForTeam(entity.id):[],current=stats.projects.filter(ongoingProject);
  $('projectModalTitle').textContent=entity.name+' — Performance data';$('projectModalBadge').textContent='View only';
  $('projectModalBody').innerHTML=`<div class="grid4"><div class="stat"><b>${current.length}</b><span>Ongoing projects</span></div><div class="stat"><b>${stats.projects.length}</b><span>Recorded projects</span></div><div class="stat"><b>${stats.completed.length}</b><span>Ended process records</span></div><div class="stat"><b>${stats.hours.toFixed(1)}</b><span>Recorded elapsed hours</span></div></div>${entity.type==='team'?`<div class="panel"><h3>Team members</h3>${members.map((p,index)=>`<button data-member-index="${index}">${escapeHtml(personName(p))} · ${escapeHtml(personRole(p))}</button>`).join(' ')||'No roster members'}</div>`:''}<div class="panel"><h3>Ongoing projects</h3>${analyticsProjectBullets(current,true)}</div><div class="panel"><h3>Projects worked on / assigned</h3>${analyticsProjectBullets(stats.projects,true)}</div><div class="panel"><h3>Current item assignments and PIC</h3>${stats.current.map(i=>`<p>${escapeHtml(i.ItemID+' · '+i.ItemDescription)} · ${escapeHtml(i.ItemStatus)} · PIC: ${escapeHtml(i.AssignedPersonnel||'Unassigned')}</p>`).join('')||'No individually recorded current items.'}</div><div class="panel"><h3>Recorded processes</h3><div class="tableScroll"><table><thead><tr><th>SO / Item</th><th>Process</th><th>PIC</th><th>Start</th><th>End</th><th>Remarks</th></tr></thead><tbody>${stats.logs.map(h=>`<tr><td>${escapeHtml(h.SONumber+' / '+h.ItemID)}</td><td>${escapeHtml(h.ToValue)}</td><td>${escapeHtml(h.Personnel||'Unassigned')}</td><td>${niceDT(h.StartedAt)}</td><td>${h.FinishedAt?niceDT(h.FinishedAt):'Ongoing'}</td><td>${escapeHtml(h.Message)}</td></tr>`).join('')||'<tr><td colspan="6">No recorded processes attributed to this person or team.</td></tr>'}</tbody></table></div></div>`;
  $('projectModalFooter').innerHTML='<button id="analyticsBack">← Back</button><button data-close="projectModal">Close</button>';$('analyticsBack').onclick=analyticsBack;bindStatusLinks($('projectModalBody'),()=>openAnalyticsEntity(entity,{backNavigation:true}));$('projectModalBody').querySelectorAll('[data-member-index]').forEach(b=>b.onclick=()=>openAnalyticsEntity({id:members[Number(b.dataset.memberIndex)].PersonnelID,name:personName(members[Number(b.dataset.memberIndex)]),type:'person'}));openModal('projectModal');
}
